name = "large-video-uploader"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[vars]
ACCOUNT_ID = "d9bfc18ff0adcec738cf58c0fbf3432a"

[env.production]
vars = { ACCOUNT_ID = "d9bfc18ff0adcec738cf58c0fbf3432a" }

[secrets]
# R2_ACCESS_KEY_ID
# R2_SECRET_ACCESS_KEY

